[FIGHTER_1]
type = "Thing"
roles = "WEAPON"

[FIGHTER_2]
types = ["Thing"]

[DRAMA]


[[_]]
label = "opening"

if = {}

-="""
<FIGHTER_1:say>

{ DRAMA.state.name }

"""

do = {}


# Also TODO
# text pipelines
# eg:
# raw -> substitutions
# raw -> substitutions -> markdown -> transforms

