[FIGHTER_1]
type = "balladeer.Persona"
roles = "WEAPON"

[FIGHTER_2]
types = "balladeer.Persona"

[DRAMA]


[[_]]
[[_.if]]

[[_.if]]
# role
# line

[[_._]]

[[_.do]]

[[_.do]]

0 = "Hell!"

# Also TODO
# text pipelines
# eg:
# raw -> substitutions
# raw -> substitutions -> markdown -> transforms

