[FIGHTER_1]
type = "balladeer.Persona"
roles = "WEAPON"

[FIGHTER_2]
types = "balladeer.Persona"

[DRAMA]


[[_]]
label = "opening"

if = {}

it = """
<FIGHTER_1:say>

{ DRAMA.state.name }

"""

do = {}


# Also TODO
# text pipelines
# eg:
# raw -> substitutions
# raw -> substitutions -> markdown -> transforms

