[FIGHTER_1]
type = "Thing"
roles = "WEAPON"
states = [1]

[FIGHTER_2]
types = ["Thing"]
states = [1]

[DRAMA]


[[_]]
label = "opening"

if = {}

-="""
<FIGHTER_1:say>

I hate you, { FIGHTER_2["name"] }!

"""

do = {
"FIGHTER_1": [0],
}


# Also TODO
# text pipelines
# eg:
# raw -> substitutions
# raw -> substitutions -> markdown -> transforms

