# Scene
[scene]
# scene roles
# scene conditions

[[shots]]
# Shot 1..n
# conditions

# role
# line

# Also TODO
# text pipelines
# eg:
# raw -> substitutions
# raw -> substitutions -> markdown -> transforms
[[shots]]
foo = 1
