[FIGHTER_1]
type = "Thing"
roles = "WEAPON"
states = [1]

[FIGHTER_2]
types = ["Thing"]
states = [1]

[DRAMA]


[[_]]
if.FIGHTER_1.states = [1]

-="""
<FIGHTER_1:says>

I hate you, { FIGHTER_2["name"] }!

"""

do.FIGHTER_1.states = [0]


[[_]]
if.FIGHTER_1.states.int = 1
-="""
<FIGHTER_1:says?pause=1&dwell=0.3>

I hate you, { FIGHTER_2.name }!

"""
do.FIGHTER_1.states.int = 0

