[FIGHTER_1]
type = "balladeer.Persona"
roles = "WEAPON"

[FIGHTER_2]
types = "balladeer.Persona"

[DRAMA]


[[_]]

if = 1

it = """
<fighter_1:say>


"""

do = 2


# Also TODO
# text pipelines
# eg:
# raw -> substitutions
# raw -> substitutions -> markdown -> transforms

