project = "Balladeer JS frontend example"

[BOTTLE]
type = "Bottle"
state = 1

[PERFORMANCE]
type = "Song"

[[_]]
# Many bottles
s="""
<>  {PERFORMANCE} green bottles, hanging on the wall.
"""

[[_]]
# One bottle
s="""
<>  {PERFORMANCE} [green bottle](https://www.onegreenbottle.com/), hanging on the wall.
"""

[[_]]
# All cases
s="""
<>  And if one green bottle should *accidentally* fall,
    There'll be...
"""

# DRAMA.prompt Type 'look' to check
