[DRAMA]
type = "Adventure"
state = "Spot.cloakroom"

[GARMENT]
type = "Clothing"

[HANGER]
type = "Fixture"


[[_]]
if.DRAMA.states.Detail = ["none"]
s="""
You find yourself in a gloomy space which smells strongly of damp.
It has a partition which makes a small anteroom near the doorway, leaving a much larger area behind.

"""

[[_]]
if.DRAMA.states.Detail = ["here"]
s="""
<>  This is a cloakroom for patrons of the bar.
	At eye-level there is an array of metalwork which vaguely resembles a line of coat hooks.
	All are gone, witnessed only by broken brass baseplates or rotten screw holes.

<>  No, wait; there is one. One coat hook survives.
"""

[[_]]
if.HANGER.state = 0
if.GARMENT.states.Spot = ["cloakroom"]
s="""
<>  Your cloak lies in a heap on the floor.
"""

[[_]]
if.HANGER.state = 1
if.GARMENT.states.Spot = ["cloakroom"]
s="""
<>  Your velvet cloak hangs darkly from the hook.
"""
