[DRAMA]
type = "Adventure"
state = "Spot.cloakroom"

[GARMENT]
type = "Clothing"

[HANGER]
type = "Fixture"


[[_]]
if.DRAMA.states.Detail = ["none", "hint"]
s="""
You find yourself in a gloomy space which smells strongly of damp.
It has a partition which makes a small anteroom near the doorway, leaving a much larger area behind.

"""

[[_]]
if.DRAMA.states.Detail = ["here"]
if.HANGER.state = 1
s="""
<>  This is a cloakroom for patrons of the bar.
	At eye-level there is an array of metal scars; the remains of a line of coat hooks.
	All are gone but for broken brass baseplates and rotten screw holes.

<>  OK, so there *is* one. One coat hook survives.
"""

[[_]]
if.DRAMA.states.Detail = ["hint"]
s="""
<>  Try these commands:

    + 'Look' to see more detail.
    + 'Inventory' to learn what you are carrying.

    Or perhaps you should make use of the facilities?
"""

[[_]]
if.HANGER.state = 1
if.GARMENT.states.Spot = ["cloakroom"]
s="""
<>  Your cloak lies in a heap on the floor.
"""

[[_]]
if.HANGER.state = 0
if.GARMENT.states.Spot = ["cloakroom"]
s="""
<>  Your velvet cloak hangs darkly from the hook.
"""
