[DRAMA]
type = "Adventure"
state = "Spot.foyer"

[GARMENT]
type = "Clothing"

[[_]]
if.DRAMA.states.Detail = ["here"]
s="""
<>  This shell of a building was once a hotel.

    Right here would have been a foyer.
    You can see the footprint of a grand reception desk running down one side
    of the floor.

"""

[[_]]
if.DRAMA.states.Detail = ["none"]
s="""
<>  The room has been stripped of all it once contained.
"""

[[_]]
if.GARMENT.states.Spot = ["inventory"]
s="""
<>  You are wearing a long cloak, which gathers around you.
"""
