[DRAMA]
type = "Adventure"
state = "Spot.foyer"

[[_]]
s="""
<>  {DRAMA.state} green bottles, hanging on the wall.

"""

[[_]]
# One bottle
if.DRAMA.state = 1
s="""
<>  {DRAMA.state} [green bottle](https://www.onegreenbottle.com/), hanging on the wall.

"""
