[FIGHTER_1]
roles = ["WEAPON"]

[FIGHTER_2]
type = "Animal"

[WEAPON]
type = "Weapon"

[[_]]

s="""
<FIGHTER_1>

    I don't like the way you use me, {FIGHTER_2.name}!

<WEAPON.attacking@FIGHTER_2:shouts/slapwhack?offer=1>

    _Whack!_

"""

[[_]]

s="""
<FIGHTER_2>

    Uuurrggh!

"""
